### ISSUE TITLE
Читаемость кода

### ISSUE THREAD

**Issue by v-excelsior** [TimSeryakov/friday-exam#1]
https://github.com/TimSeryakov/friday-exam/blob/05243de133ad2ce9ac7c0cfa16f79708f14dce09/src/components/Button/Button.tsx#L12

Мне кажется такие строки очень сильно ухудшают читаемость кода, ты мог бы использовать функцию `getClasses`
которая имела бы вид вроде такого
```javascript
const getClasses = () = {
  const {one,two} = props  // это избавляет от надобности писать props.one

  const classes = [] //сюда можешь положить классы которые будут в любом случае  к примеру bg-theme-dark

  if (one) {
    classes.push('some-class-1')
  }

  classes.push( two ? 'foo' : 'bar')

  return classes.join(' ')
}
```
Так же я думаю можно в этом компоненте убрать value, т.к. это выбивается из того как обычно мы используем кнопку
`<btn> Some label </btn>`
Можешь просто проксировать props.children (там где props.value писать props.children и использовать синтаксис как выше)

И последняя придирка скорее - value - это значение, а то что написано на кнопке это label

**Comment by TimSeryakov** [comment]
спасибо за ревью! не совсем понял этот момент с getClasses - чем лучше использование отдельной функции, чем тернарника с точки зрения читабельности? KISS) Но, возможно, такой подход будет действительно неплох при большом количестве классов и разветвлённой логике.

На счет children согласен, просто не знал о нем на момент решения этой задачки, надо переделать

🤝😉

**Comment by TimSeryakov** [comment]
Зарефакторил, получилось покрасивее

**Comment by v-excelsior** [comment]
Собственно ты сам ответил на свой вопрос. Легче найти -> легче исправить. Допустим у кнопки будут разные хендлеры в зависимости от пропсов, разные классы, разные лейблы, разные темы, разные размеры ( пример притянут за уши, просто думай о компоненте чуть сложнее)

И тогда его код с моим подходом будет 
```
<btn
    classes={ () = {getClasses(someProps) }
    handlers={ () = {getHandler(someProps) }
    label={ ()={ getLabel(text) }
>

или там

<btn
    classes={`${foo} ${isTrue ? 'trueClass' : 'falseClass' bar buz another class some-very-logs-class` }
    handlers={ action === 'goToPage' ? () = {goToPage() : action === 'notGoToPage' ? () => {notGoToPage()} : ()=>{doNothing()} }
    label={`${action === 'goToPage' ? 'Go to page' : 'Not go to page' }
> 

А если получится выделить от сюда кусок кода, и вынести его в какие-то хелперы, так еще лучше будет.
И это больше предложения рекомендательного характера, я сам не очень опытен, посмотри попробуй и сделай как считаешь нужным.

upd: Tailwind руками зло :)

**Comment by TimSeryakov** [comment]
аа, понял о чем ты. при разрастании логики\классов определенно надо выносить за пределы. похожим образом я выносил класс [здесь](https://github.com/TimSeryakov/ignat-tasks-tw/blob/master/src/components/common/CustomButton/CustomButton.tsx), только не в fn, а в переменную (там так себе решение - PurgeCSS таким образом не работает, так что пришлось ручками писать whitelist классов в tailwind.config.js).

не уловил, почему Tailwind руками зло?

**Comment by v-excelsior** [comment]
У компонентов со сложными стилями у тебя классы будут разрастаться на несколько строк, выглядит ужастно. Есть пути более сложные, но елегантные. Например фейсбук на сколько мне известно пишет стили по какой-то из методологий( если не знаком то почитай про BEM - разработка яндекса, и OOCSS) а потом это все собирают в tailwind, при этом бандл стилей минимальный и после определенного периода просто не растет, а файлы стилей остаются читаемыми.

Можешь закрыть это ишью, что бы оно не висело.

**Comment by TimSeryakov** [comment]
fb собирают свои стили в tailwind? ты видимо путаешь TailwindCSS с чем-то похожим

ps. пришел из верстки если что 😉

**Comment by v-excelsior** [comment]
![image](https://user-images.githubusercontent.com/15347646/96036809-a953d600-0e6d-11eb-916b-1c12a0539ee7.png)
Можешь сам проверить, эти хеши это tailwind классы, отключишь любой их них и страница поплывет во всех местах.

**Comment by TimSeryakov** [comment]
Хм.. Мы говорим о [TailwindCSS ](https://tailwindcss.com/ )который разработал [Adam Wathan](https://adamwathan.me/)?

**Comment by v-excelsior** [comment]
Возможно я ошибаюсь где-то в понятиях, но я воспринимаю tailwind не как конкретную технологию, а как подход описывать стили утилитарными классами.
А сама технология это просто более удобная API для этих же утилитарных классов, много из которых ты сам просто не пишешь, а используешь уже готовые.
Я даже уверен что конкретно то что ты линканул, им смысла использовать нет.

**Comment by TimSeryakov** [comment]
Теперь понятно. Посмотри https://tailwindcss.com/ у них очень интересный подход, особенно в вопросе реализации адаптивности. Кастомный CSS тебе просто перестаёт быть нужен.
